# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# covr : https://covr.r-lib.org

language: r
r_packages:
    - covr
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
warnings_are_errors: false

