on: [push, pull_request]
name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      R_COMPILE_AND_INSTALL_PACKAGES: never
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1

      - name: Install dependencies
        run: |
          install.packages(c("BiocManager"))
          BiocManager::install(c("ggbio", "covr"))
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
